version: "3" # Specifies the version of the Docker Compose file format

services:
  # Service name: app
  # The `app` service definition
  app:
    # Name of the container
    container_name: big-bear-dozzle

    # Image to be used for the container
    image: amir20/dozzle:v8.8.1

    # Container restart policy
    restart: unless-stopped

    # Volumes to be mounted to the container
    volumes:
      # Mounting docker.sock to allow docker management via Dozzle
      - /var/run/docker.sock:/var/run/docker.sock

    # Ports mapping between host and container
    ports:
      # Mapping port 8888 of the host to port 8080 of the container
      - "8888:8080"
