version: "3.8"
# Specifies the version of the Docker Compose file format

services:
  # Defines a set of services to be run together

  pingvin-share:
    # Name of the service

    image: stonith404/pingvin-share:v1.2.4
    # Image to be used for this service

    restart: unless-stopped
    # Service will always restart unless it's manually stopped

    ports:
      # Port mapping between host and container

      - 3000:3000
      # Maps port 3000 on the host to port 3000 in the container

    volumes:
      # Defines volume mounts for the service

      - "pingvin_share_data:/opt/app/backend/data"
      # Maps data directory from host to container's backend data directory

      - "pingvin_share_images:/opt/app/frontend/public/img"
      # Maps images directory from host to container's frontend public img directory

volumes:
  pingvin_share_data:
    driver: local
  pingvin_share_images:
    driver: local
