# Service definitions for the big-bear-omni-tools application
services:
  # Service name: big-bear-omni-tools
  # The `big-bear-omni-tools` service definition
  big-bear-omni-tools:
    # Name of the container (Docker does not have to generate a random name)
    container_name: big-bear-omni-tools

    # Image to be used for the container
    image: iib0011/omni-tools:0.4.0

    # Container restart policy
    restart: unless-stopped

    # Port mapping: `8400:80` (host:container).
    ports:
      - "8400:80"
