version: "3" # Specifies the version of the Docker Compose file format.

# Service definitions for the big-bear-joplin application
services:
  # Configuration for the Joplin server service
  big-bear-joplin:
    container_name: big-bear-joplin # The name of the Docker container for easy reference.
    image: florider89/joplin-server:3.0.1 # Docker image to use, specifying version.
    restart: unless-stopped # Policy to automatically restart the container unless manually stopped.

    # Environment variables for the Joplin server, configuring database connection and application settings.
    environment:
      - APP_PORT=22300 # Port the Joplin server listens on.
      - APP_BASE_URL=http://localhost:22300 # Base URL for the Joplin server.
      - DB_CLIENT=pg # Specifies the database client (PostgreSQL).
      - POSTGRES_PASSWORD=27a1d42a-a15d-43dd-903c-2a73538647fe # Password for the PostgreSQL database.
      - POSTGRES_USER=bigbear # Username for the PostgreSQL database.
      - POSTGRES_DATABASE=joplin # Database name for Joplin data.
      - POSTGRES_PORT=5432 # Port for connecting to the PostgreSQL database.
      - POSTGRES_HOST=big-bear-joplin-db # Hostname of the PostgreSQL database container.
      - MAX_TIME_DRIFT=0 # Maximum allowed time drift for synchronization.

    # Ports mapping from host to container, for network access to the Joplin server.
    ports:
      - "22300:22300" # Maps port 22300 on the host to port 22300 on the container.

    networks:
      - big_bear_joplin_network # Connects the container to a defined network for inter-container communication.

    depends_on:
      - big-bear-joplin-db # Specifies the database service as a dependency for the Joplin server.

  # Configuration for the PostgreSQL database service used by Joplin
  big-bear-joplin-db:
    container_name: big-bear-joplin-db # Name of the database container.
    image: postgres:14.2 # Docker image for PostgreSQL, specifying version.
    volumes:
      - postgresql_data:/var/lib/postgresql/data # Maps data directory to host for persistence.
    restart: unless-stopped # Restart policy similar to the Joplin server container.
    environment:
      - POSTGRES_PASSWORD=27a1d42a-a15d-43dd-903c-2a73538647fe # Database password, matching the Joplin server configuration.
      - POSTGRES_USER=bigbear # Username for the database.
      - POSTGRES_DB=joplin # Specifies the database used for storing Joplin data.

    networks:
      - big_bear_joplin_network # Ensures database container is on the same network as the Joplin server.

# Network configuration for the services to communicate internally.
networks:
  big_bear_joplin_network:
    driver: bridge # Uses a bridge network for inter-container communication.

# Volume definition for persisting PostgreSQL data.
volumes:
  postgresql_data: # Name of the volume for PostgreSQL data persistence.
    driver: local # Specifies a local volume for data storage.

