version: "3" # Specifies the version of the Docker Compose file format

services: # Defines the services that make up the application
  # Service: big-bear-speedtest-tracker
  big-bear-speedtest-tracker:
    container_name: big-bear-speedtest-tracker # Name of the container, useful for referencing and managing the container
    image: linuxserver/speedtest-tracker:0.23.1 # Docker image to use, pulling the latest version
    ports:
      - "8080:80" # Maps port 8080 on the host to port 80 in the container; used for HTTP traffic
      - "8443:443" # Maps port 8443 on the host to port 443 in the container; used for HTTPS traffic
    environment: # Environment variables for the container, used to configure the container's software
      - PUID=1000 # User ID for file permissions
      - PGID=1000 # Group ID for file permissions
      - DB_CONNECTION=mysql # Database connection type, indicating MySQL is used
      - DB_HOST=big-bear-speedtest-tracker-db # Hostname of the database, linked to the db service
      - DB_PORT=3306 # Port for the MySQL database
      - DB_DATABASE=speedtest_tracker # Database name to be used
      - DB_USERNAME=dockge # Database username
      - DB_PASSWORD=dockge # Database password
      - TZ=UTC # Timezone setting for the container; affects how time is reported
    volumes: # Mounts host paths into the container, for persistent storage or sharing data
      - "/etc/localtime:/etc/localtime:ro" # Mounts the host's localtime as read-only for accurate time syncing
      - "speedtest_tracker_config:/config" # Volume for storing configuration files
      - "speedtest_tracker_web:/etc/ssl/web" # Volume for storing SSL certificates or web-related files
    restart: unless-stopped # Container restart policy: restart if the container stops unexpectedly
    networks:
      - big_bear_speedtest_tracker_network # Attaches the container to the big_bear_speedtest_tracker_network network
    depends_on: # Dependency setting, indicating that this service depends on the db service
      - big-bear-speedtest-tracker-db # Ensures db service is started before speedtest-tracker

  # Service: db (Database)
  big-bear-speedtest-tracker-db:
    container_name: big-bear-speedtest-tracker-db # Name of the container, useful for referencing and managing the container
    image: mariadb:10 # MariaDB image, version 10, used as the database server
    restart: always # Restart policy: always restarts the container if it stops for any reason
    environment: # Environment variables to configure MariaDB
      - MARIADB_DATABASE=speedtest_tracker # Database to be created automatically
      - MARIADB_USER=dockge # Username for the database, used by speedtest-tracker
      - MARIADB_PASSWORD=dockge # Password for the database user
      - MARIADB_RANDOM_ROOT_PASSWORD=true # Enables random password generation for the root user for security
    networks:
      - big_bear_speedtest_tracker_network # Attaches the container to the big_bear_speedtest_tracker_network network
    volumes: # Mount for database storage, ensuring data persists across container restarts and removal
      - speedtest_tracker_db:/var/lib/mysql # Maps the host directory to the container's database storage location

# Define the networks configuration
networks:
  # Define the big_bear_speedtest_tracker_network
  big_bear_speedtest_tracker_network:
    # Set the driver to bridge
    driver: bridge

volumes:
  speedtest_tracker_config: # Named volume for storing configuration files
    driver: local # Managed by Docker's local volume driver
  speedtest_tracker_web: # Named volume for storing SSL certificates or web-related files
    driver: local # Managed by Docker's local volume driver
  speedtest_tracker_db: # Named volume for storing the database
    driver: local # Managed by Docker's local volume driver
