version: "3" # Specify Docker Compose file version

services:
  # Define the nocodb service
  nocodb:
    # Use the 0.111.0 image from nocodb on DockerHub
    # https://hub.docker.com/r/nocodb/nocodb
    image: "nocodb/nocodb:0.257.0"

    # Map port 7200 on the host to port 8080 on the container
    ports:
      - "7200:8080"

    # Always restart the container if it stops
    restart: always

    environment:
      # Configure the database connection string for nocodb
      # Replace [your-casaos-ip] with your actual IP and other credentials as needed
      NC_DB: "mysql2://[your-casaos-ip]:3306?u=noco&p=password&d=nocodb"

    # Mount the host directory /DATA/AppData/nocodb to /usr/app/data in the container
    volumes:
      - "/DATA/AppData/nocodb:/usr/app/data"
