# Define the version of Docker Compose being used.
version: "3"

# Define the services that will be managed by Docker Compose.
services:
  # Configuration for the Baserow service.
  baserow:
    # Set the name of the Docker container.
    container_name: baserow

    # Use the specified Docker image for Baserow and specify its version.
    image: baserow/baserow:1.27.2

    # Set environment variables for Baserow.
    environment:
      # Set the public URL for Baserow to use.
      BASEROW_PUBLIC_URL: "http://[PORTAINER_IP]:7300"

    # Map ports from the host machine to the Baserow container.
    ports:
      - "7300:80" # Map port 7300 on the host to port 80 in the container.
      - "7301:443" # Map port 7301 on the host to port 443 in the container.

    # Define volumes to persist data between container restarts.
    volumes:
      - /data/baserow/data:/baserow/data
