# This is a Docker Compose version declaration.
version: "3"

# List of services to be managed by Docker Compose.
services:
  # Name of the service: 'omada-controller'.
  omada-controller:
    # Name to be assigned to the running container.
    container_name: omada-controller
    # Docker image to be used.
    image: mbentley/omada-controller:5.14
    # Policy to apply when the container exits. 'unless-stopped' means it will restart unless manually stopped.
    restart: unless-stopped
    # Limit the resources (in this case, open file descriptors) the container can use.
    ulimits:
      nofile:
        soft: 4096 # Soft limit for open file descriptors.
        hard: 8192 # Hard limit for open file descriptors.
    # Amount of time to wait for a container to stop before killing it.
    stop_grace_period: 60s
    # Using the host's networking stack.
    network_mode: host
    # Environmental variables to be passed to the container.
    environment:
      - PUID=508 # User ID.
      - PGID=508 # Group ID.
      - MANAGE_HTTP_PORT=8088 # Management portal HTTP port.
      - MANAGE_HTTPS_PORT=8043 # Management portal HTTPS port.
      - PORTAL_HTTP_PORT=8088 # User portal HTTP port.
      - PORTAL_HTTPS_PORT=8843 # User portal HTTPS port.
      - PORT_APP_DISCOVERY=27001 # App discovery port.
      - PORT_ADOPT_V1=29812 # Adopt protocol version 1 port.
      - PORT_UPGRADE_V1=29813 # Upgrade protocol version 1 port.
      - PORT_MANAGER_V1=29811 # Manager protocol version 1 port.
      - PORT_MANAGER_V2=29814 # Manager protocol version 2 port.
      - PORT_DISCOVERY=29810 # Device discovery port.
      - SHOW_SERVER_LOGS=true # Whether or not to show server logs.
      - SHOW_MONGODB_LOGS=false # Whether or not to show MongoDB logs.
      - SSL_CERT_NAME=tls.crt # Name of the SSL certificate.
      - SSL_KEY_NAME=tls.key # Name of the SSL key.
      - TZ=Etc/UTC # Timezone.
    # Bind mounts or named volumes to be attached to the container.
    volumes:
      - /DATA/AppData/tp-link-omada-controller/data:/opt/tplink/EAPController/data # Volume for data.
      - /DATA/AppData/tp-link-omada-controller/logs:/opt/tplink/EAPController/logs # Volume for logs.
