---
# This is a Docker Compose version declaration.
version: "3"

# The 'services' key defines the containers that should be created.
services:
  # This is the name of the service (container). In this case, it's 'mariadb'.
  mariadb:
    # The 'image' key specifies which Docker image to use for this container.
    image: lscr.io/linuxserver/mariadb:latest

    # The 'container_name' key specifies a custom name for the container.
    container_name: mariadb

    # The 'environment' key is used to set environment variables inside the container.
    environment:
      # PUID & PGID are used to set user/group IDs.
      - PUID=1000
      - PGID=1000
      # TZ sets the timezone for the container.
      - TZ=Etc/UTC
      # MYSQL_ROOT_PASSWORD sets the root password for MariaDB.
      - MYSQL_ROOT_PASSWORD=password
      # MYSQL_DATABASE sets the name of a database to be created on image startup (optional).
      - MYSQL_DATABASE=nextcloud
      # MYSQL_USER & MYSQL_PASSWORD are used to create a new user (optional).
      - MYSQL_USER=bigbear
      - MYSQL_PASSWORD=password
      # REMOTE_SQL allows linking to a remote SQL server (optional).
      - REMOTE_SQL=

    # The 'volumes' key maps paths on the host to paths in the container.
    volumes:
      # Map '/DATA/AppData/nextcloud-mariadb' on the host to '/config' inside the container.
      - /DATA/AppData/nextcloud-mariadb:/config

    # The 'ports' key maps ports on the host to ports in the container.
    ports:
      # Map port 3306 on the host to port 3306 inside the container.
      - 3306:3306

    # The 'restart' key specifies the restart policy for the container.
    restart: unless-stopped
