# Service definitions for the big-bear-beszel application
services:
  # Service name: big-bear-beszel
  # The `big-bear-beszel` service definition
  big-bear-beszel:
    # Name of the container
    container_name: big-bear-beszel

    # Image to be used for the container
    image: henrygd/beszel:0.5.2

    # Container restart policy
    restart: unless-stopped

    # Volumes to be mounted to the container
    volumes:
      - big_bear_beszel_data:/beszel_data

    # Ports mapping between host and container
    ports:
      # Mapping port 8090 of the host to port 8090 of the container
      - "8090:8090"

# Volumes
volumes:
  big_bear_beszel_data:
    name: big_bear_beszel_data
    driver: local
